/mauv_3/imu_driver_node:
    ros__parameters:
      roll_offset: 3.1415926
      pitch_offset: 0.0
      yaw_offset: 1.5707
      roll_reverse: 1.0
      pitch_reverse: -1.0
      yaw_reverse: -1.0

/mauv_3/thruster_driver_node:
    ros__parameters:
      thruster_pub_topic: /mauv_3/stonefish/thruster_command
      thruster_length: 4
      thruster_sub_topics: [/mauv_3/control/thruster/surge, 
                          /mauv_3/control/thruster/sway_bow, 
                          /mauv_3/control/thruster/heave_stern, 
                          /mauv_3/control/thruster/heave_bow]

/mauv_3/dvl_driver_node:
    ros__parameters:
      dvl_in: /mauv_3/dvl/stonefish/raw
      dvl_out: /mauv_3/dvl/twist
      dvl_alt_out: /mauv_3/dvl/altitude